name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      text1:
        description: 'Input text 1'     
      text2:
        description: 'Input text 2'

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.md
              path: /home/runner/work/devops-school/devops-school/log.md
        - name: 1.4 TEST TEXT INPUT
          run: |
            echo "Text message"
            echo "Text1: ${{ github.event.inputs.text1 }}"
            echo "Text2: ${{ github.event.inputs.text2 }}" 
